export const GET_FAMILIES = 'GET_FAMILIES';
export const GET_FAMILIES_SUCCESS = 'GET_FAMILIES_SUCCESS';
export const GET_FAMILIES_FAILURE = 'GET_FAMILIES_FAILURE';
export const REMOVE_FAMILY = 'REMOVE_FAMILY';
export const ADD_FAMILY = 'ADD_FAMILY';
